[project]
name = "openstd_spider"
version = '0.1.1'
description = "国家标准全文公开系统下载工具"
authors = [{ name = "SocialSisterYi", email = "1440239038@qq.com" }]
urls = { Repository = "https://github.com/SocialSisterYi/OpenSTD_Spider" }
dependencies = [
    "httpx>=0.28.1",
    "opencv-python>=4.11.0.86",
    "numpy>=2.2.3",
    "beautifulsoup4>=4.13.3",
    "ddddocr>=1.5.6,<1.6.0",
    "lxml>=5.3.1",
    "reportlab>=4.3.1",
    "typer>=0.15.1",
    "rich>=13.9.4",
    "dataclasses-json>=0.6.7",
    "aiofiles>=25.1.0",
    "fastapi>=0.115.8",
    "uvicorn[standard]>=0.34.0",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "GPLV3" }
scripts = { openstd_spider = "openstd_spider.__main__:app", openstd_spider_web = "openstd_spider.web:main" }


[tool.pdm]
distribution = true

[tool.setuptools.package-data]
openstd_spider = ["web_static/*.html"]

[tool.black]
line-length = 120
